const CASH_MOVEMENT_TYPES = {
    CASH_IN: 'CASH_IN',
    CASH_OUT: 'CASH_OUT',
    SALE: 'SALE',
    REFUND: 'REFUND'
};

const CASH_MANUAL_MOVEMENT_TYPE_VALUES = [
    CASH_MOVEMENT_TYPES.CASH_IN,
    CASH_MOVEMENT_TYPES.CASH_OUT
];

module.exports = {
    CASH_MOVEMENT_TYPES,
    CASH_MANUAL_MOVEMENT_TYPE_VALUES
};